string command      # "HTTP GET /{command}...
int64 u             # "/set_*_ctrl?u={u}
int64 target_brick  # "/set_*_target_brick?target_brick={target_brick}
float64 target_mm        # "/set_*_target_mm?target_mm={target_mm}
int64 plunger_target
---
string status